name: "CI"
on: [pull_request, push]

jobs:
  # make sure build/ci work properly
  build:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Test Action
      run: |
        npm install
        npm run all

  # make sure the action works on a clean machine without building
  test:
    name: E2E test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Download test file
      run: |
        curl -Ls https://github.com/svenstaro/proxyboi/releases/download/0.1.5/proxyboi-linux-amd64 -o testbinary
        chmod +x testbinary
        cp testbinary testbinary.glob1
        cp testbinary testbinary.glob2
    - name: Test Action
      uses: ./
      with:
        files: |
          testbinary
        args: --best --lzma

    - name: Test Action with glob
      uses: ./
      with:
        files: |
          *.glob*
        args: --best --lzma
